Fix inconsistent sorting of department scores
campaignzero/police-scorecard pull request #23
Opened 2020-09-09 06:04 UTC by manifestinteractive

Overview:
---

Also updated max departments from 500 to 1,000.

Reviewer:
---

> Where should the reviewer start? How to Test? Background Context? etc ( required )

Home page sorting was correct, but report pages had the order backwards.

Checklist:
---

> I have tested each of the following, and they work as expected: ( required )

- [X] Meets [Contributing Guide](https://github.com/campaignzero/police-scorecard/blob/develop/.github/CONTRIBUTING.md) Requirements
- [X] Pulled in the Latest Code from the `develop` branch
- [X] Works on a Desktop / Laptop Device
- [X] Works on a Mobile Device
- [X] `npm test` Does Not Generate Errors

Documentation:
---

> Screenshots, Attachments, Linked GitHub Issues, etc ( optional )

Fixes #4 & #8 

#### What GIF best describes this PR or how it makes you feel?

> Drag & Drop Something Fun Here ( optional )

![that_a_boy](https://user-images.githubusercontent.com/508411/92560619-b6fbb780-f240-11ea-9cc2-672fda69913c.gif)

2020-09-09 20:04 UTC, MasterInTraining23 requested changes

2020-09-09 21:11 UTC, manifestinteractive commented on app/View/Components/Partial/Grades.php
> +        $this->grades = array_slice($grades, 0, 1000);
Class variable adds one time use as a permanent property, which bloats the class.  This is just truncating the data in the constructor and that variable will never be used again.  Happy to change if you still want, but this was intentional.

2020-09-09 21:12 UTC, manifestinteractive commented on routes/web.php
> +    // Sort Grades
probably makes sense to do this on the API call itself where it is getting this data.  I was just being lazy, good call.

2020-09-09 21:51 UTC, MasterInTraining23 commented on app/View/Components/Partial/Grades.php
> +        $this->grades = array_slice($grades, 0, 1000);
For me, the readability benefits of a static variable outweigh the memory alloc in this scenario. However, I think it's totally fine to leave it as is and simply remove the comment.

2020-09-09 23:49 UTC, manifestinteractive commented
@MasterInTraining23 this is ready for you to review again.  Cleaned up everything as requested.

2020-09-10 02:54 UTC, MasterInTraining23 approved these changes

2020-09-10 03:12 UTC, merged